### ISSUE TITLE
Team wants hacker - mobile friendly Ethereum faucet

### ISSUE THREAD

**Issue by davecraige** [ethberlin-hackathon/ETHBerlin-Teambuilding#8]
## Pitch

We want to build a mobile friendly Ethereum faucet that is beautiful and "just works" 

## Team

We already have a few of people interested to help us a bit with design.   Hit me up to meet the team.

## Skills wanted

All developers are welcome!
- solidity
- front end
- back end
- Junior developers
- Senior developers

All designers are welcome!
- UI
- UX
- Junior designers
- Senior designers

## Communication

Please send me a message on:
Twitter: http://www.twitter.com/DaveCraige 
Discord: http://www.DaveCraige.com/discord 
Email: Dave@Tugboat.io

_Look forward to meeting you!_

**Comment by ligi** [comment]
That's a great idea! One important feature is you can pass the address so people do not have to copy and paste and UX is a bit nicer this way - @sponnet was recently nicely and fast adding this to the ropsten faucet: https://twitter.com/sponnet/status/1030501496566292481

Feature-wise it would also be awesome if the faucet could work across different test-nets and also spits out some test tokens alongside the test-eth. Not sure if you need Android developers here - but if you do - please hit me up. Otherwise I would just directly add it to @walleth as part of https://github.com/walleth/walleth/issues/273 - ping me when it is ready to add - or you can directly PR it like this: https://github.com/walleth/kethereum/blob/master/networks/src/main/kotlin/org/walleth/data/networks/all/NetworkDefinition3.kt#L14

PS: wonder what ideas you have regarding drain prevention. I think this is the most important thing to get UX on mobile well. The auth flow via post on twitter/fb/g+ like the rinkeby faucet is doing (https://faucet.rinkeby.io) - is very bad UX on mobile unfortunately (which makes me sad as rinkeby is the test-network I like most otherwise) - the ip based drain prevention which the ropsten faucet by @sponnet is doing is very nice regarding UX - but might be abused at some point. Wonder what you plan to do.

Also perhaps ask before the hackathon so you can get some funds for your faucets ( ping @karalabe for rinkeby ether, @5chdn might be able to help with kovan eth and perhaps @sponnet has ideas where to get ropsten test-eth)

**Comment by sponnet** [comment]
I can share some of my ropsten eth too

**Comment by 5chdn** [comment]
Happy to give away huge amounts of kovan and ropsten eth :)

**Comment by sponnet** [comment]
The current iteration of the ropsten faucet is here: https://faucet.ropsten.be,  code is here https://github.com/sponnet/locals-faucetserver.  If you can get some inspiration there feel free to cherry pick, or if you have any questions let me know.

**Comment by mariapaulafn** [comment]
#5

**Comment by ligi** [comment]
Was talking to @karalabe a bit (https://discordapp.com/channels/482467812179181568/482483750194774017). He is a bit resilient here as the faucet is an important DDoS protection for rinkeby. So it really depends on how you plan to protect the faucet from being drained by malicious actors. As I am mainly a fan of not needing to enter a password I think a captcha might be one option. But a captcha could only spit out small amounts. Also he would prefer if the faucet gets build on top of the existing one. I think this would make sense as we should not reinvent the wheel.

**Comment by karalabe** [comment]
The faucet included in go-ethereum is based on the LES light client protocol. However the backing node is not really important, it could also be a remote RPC endpoint, thus supporting any network, even ones that Geth does not.

The reason I'd vote for extending rather than reinventing is because the current faucet already kind of works well (issues are due to LES, not the faucet code), and already provides an extended functionality wrt different auth methods, funding tiers, captchas, etc. It would be simpler and generally more useful to make something already integrated work better than create an own one just for the kick of it.

**Comment by sponnet** [comment]
The ropsten faucet that I've been running since mid 2016 has a rate limit (1 eth every 30 seconds) , an ip and and address greylist (24h) Further than that it doesn't require a sign-up or other form of validation. Haven't had problems with it so far. 

Just my 2 Wei..

**Comment by ligi** [comment]
Unfortunately the ip and address greylist do not really help to protect. Addresses are easy to generate and IPs easy to change (e.g. using tor). And ropsten had its fair share of problems - don't want to say that was caused by your faucet - but I also understand the urge to have a stable testnet (this is why I prefer using rinkeby over ropsten) - so I think it is important to make the right trade-off between convenience and protection.

**Comment by ligi** [comment]
Did you build it? Unfortunately I do not find it on DevPost: https://ethberlin.devpost.com/submissions/search?utf8=✓&terms=faucet

**Comment by shubhamoy** [comment]
@karalabe Could you please send 5 rinkeby ethers to 0x297380a389748c14b99c58961b3d6604c0bc9e23 TIA

**Comment by ligi** [comment]
@shubhamoy the faucet is back online
